server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location = / {
        try_files /index.html =404;
    }

    location = /script.js {
        default_type application/javascript;
        add_header Content-Type "application/javascript; charset=utf-8";
    }

    location = /style.css {
        default_type text/css;
        add_header Content-Type "text/css; charset=utf-8";
    }

    location = /index.html {
        default_type text/html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
